### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mehdiboufen** [luckydhakrey/INSTAGRAM-INFO#1]
error

**Comment by mehdiboufen** [comment]
+] getting profile ...Traceback (most recent call last):
  File "/home/kali/INSTAGRAM-INFO/main.py", line 16, in <module>
    ig = main(user=args["username"])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/INSTAGRAM-INFO/api.py", line 59, in __init__
    self.get_profile()
  File "/home/kali/INSTAGRAM-INFO/api.py", line 66, in get_profile
    self.data = json.loads(more_data[3].get_text()[21:].strip(';'))
                           ~~~~~~~~~^^^
IndexError: list index out of range
